### ISSUE TITLE
Nothing happen on MAMP

### ISSUE THREAD

**Issue by bugsysop** [51seven/kirby-image-optimizer#3]
No scalling, no compression...

Configuration:

- OSX 10.12.3
- MAMP 3.5
- PHP 7.0
- Apache 2.2.29
- Kirby 2.4.1

Plugin installed in `plugins/imageoptim/`
and actived in `config.php`

**Comment by zvaehn** [comment]
please check your `php_error.log` and send me the output.

--
Please not that Kirby supports file resizing with caching since 2.3:
https://getkirby.com/docs/cheatsheet/file/resize
